export const shopPolicies = [
  "All items can be exchanged for magical equivalents within 30 days of purchase.",
  "Customers may bring their own enchanted items for trade-in at any time.",
  "In case of dissatisfaction, customers are entitled to a free consultation with a sorcerer.",
  "All sales are subject to approval by the shop's resident dragon.",
  "Payment in gold, gems, or mystical artifacts only.",
  "Customers are encouraged to haggle with the shop's talking animals for better prices.",
  "Refunds are granted if the customer can prove the item didn't perform as described in the ancient prophecies.",
  "Shoplifting will result in being cursed by the shop's enchanted guardian.",
  "Discounts available for heroes, wizards, and fairies.",
  "Customers must pass a magical test before purchasing certain high-level items.",
  "Complimentary potion tasting available for all patrons.",
  "Any item purchased under a full moon can be returned for double the value.",
  "Lost or stolen items will be tracked by the shop's mystical surveillance system.",
  "Customers may request a blessing from the shop's resident deity upon purchase.",
  "All purchases come with a free spell scroll of protection.",
  "Magical loyalty cards available for repeat customers.",
  "Customers may borrow spellbooks from the shop's library for a nominal fee.",
  "Rain checks provided for out-of-stock magical ingredients.",
  "Items enchanted with dark magic may only be sold to those with a license from the Council of Elders.",
  "Free shipping on all orders enchanted with the shop's teleportation spell.",
  "Eldritch creatures may be summoned for entertainment purposes during special events.",
  "Customers are advised to wear protective charms when handling cursed artifacts.",
  "Price matching available for spells and potions found cheaper at competing shops.",
  "Shop is closed during solar eclipses for safety reasons.",
  "Customers must sign a magical contract before purchasing time-traveling artifacts.",
  "The shop's fortune-teller offers free readings with every purchase over a certain amount.",
  "All sales final on items enchanted with unpredictable magic.",
  "Shop hours may vary depending on the alignment of the stars.",
  "Discounts available for those who solve the riddles guarding secret treasures hidden within the shop.",
];
